"""Fine-tune D-FINE-L on the annotated seat crops.

    python tools/finetune_dfine.py --dataset data/dataset \
        --dfine-root third_party/D-FINE \
        --weights models/dfine/dfine_l_obj2coco.pth

Starts from the Objects365-pretrained checkpoint rather than the COCO-only one.
Objects365 carries far more small-object supervision, and every object this
system cares about is small: the phone footprint measured on this corpus is
about 30x20 px (PRD 5.2).

This is a driver, not a reimplementation. It performs the preflight checks that
are easy to get wrong and expensive to discover an hour into a run, writes a
config, and hands off to the upstream trainer. Every check below corresponds to
a way a run can look healthy and produce a worse detector than the one it
replaced.

Preflight
---------
  * the dataset exists and both splits parse as COCO
  * the category list matches what the pipeline will ask the model for
  * validation carries labels, so its AP is computed over something
  * negatives are present, since false positives are the measured failure
  * a GPU is visible, and its memory is stated up front
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from classroom.annotate import BOX_CLASSES, NEGATIVE_CLASSES  # noqa: E402

CONFIG_TEMPLATE = """\
# Generated by tools/finetune_dfine.py. Edit the generator, not this file.
__include__: [
  '{dfine_root}/configs/dataset/coco_detection.yml',
  '{dfine_root}/configs/runtime.yml',
  '{dfine_root}/configs/dfine/include/dataloader.yml',
  '{dfine_root}/configs/dfine/include/optimizer.yml',
  '{dfine_root}/configs/dfine/include/dfine_hgnetv2.yml',
]

output_dir: {output_dir}

DFINE:
  backbone: HGNetv2

HGNetv2:
  name: 'B4'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  pretrained: True

# Objects365 weights, loaded as a starting point rather than resumed. `tuning`
# skips the optimiser and epoch state; `resume` would try to continue someone
# else's schedule.
tuning: {weights}

num_classes: {num_classes}
remap_mscoco_category: False

train_dataloader:
  dataset:
    img_folder: {img_folder}
    ann_file: {train_ann}
    return_masks: False
  shuffle: True
  total_batch_size: {batch_size}
  num_workers: 4

val_dataloader:
  dataset:
    img_folder: {img_folder}
    ann_file: {val_ann}
    return_masks: False
  shuffle: False
  total_batch_size: {batch_size}
  num_workers: 4

epoches: {epochs}

optimizer:
  type: AdamW
  params:
    -
      # The backbone already knows what small dark rectangles look like from
      # Objects365. What it does not know is this room. A tenth of the head's
      # learning rate keeps those features rather than washing them out against
      # a few hundred boxes.
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: {backbone_lr}
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.
  lr: {lr}
  betas: [0.9, 0.999]
  weight_decay: 0.0001
"""


def load_split(path: Path) -> dict:
    if not path.exists():
        raise SystemExit(
            f"{path} does not exist. Run tools/export_dataset.py first."
        )
    data = json.loads(path.read_text(encoding="utf-8"))
    for key in ("images", "annotations", "categories"):
        if key not in data:
            raise SystemExit(f"{path} is not a COCO file: no {key!r} key")
    return data


def preflight(dataset: Path, dfine_root: Path, weights: Path) -> tuple[dict, dict]:
    train = load_split(dataset / "train.json")
    val = load_split(dataset / "val.json")

    names = [c["name"] for c in sorted(train["categories"], key=lambda c: c["id"])]
    if tuple(names) != BOX_CLASSES:
        raise SystemExit(
            "the exported categories do not match classroom.annotate.BOX_CLASSES:\n"
            f"  dataset:  {names}\n  expected: {list(BOX_CLASSES)}\n"
            "Re-export, or the trained class indices will not line up with what "
            "the pipeline asks for at inference."
        )
    if not val["annotations"]:
        raise SystemExit(
            "the validation split has no annotations, so its AP would be "
            "computed over nothing. Hold out a camera that has labels."
        )
    negative_ids = {
        c["id"] for c in train["categories"] if c["name"] in NEGATIVE_CLASSES
    }
    negatives = sum(
        1 for a in train["annotations"] if a["category_id"] in negative_ids
    )
    if negatives == 0:
        raise SystemExit(
            "no negative boxes in the training split. The measured failure on "
            "this corpus is false positives on computer mice, keyboards and "
            "monitor bezels (PRD 8.1.2); a positives-only fine-tune cannot fix "
            "it and may make it worse."
        )

    if not dfine_root.exists():
        raise SystemExit(
            f"{dfine_root} not found. Clone the upstream trainer:\n\n"
            f"    git clone https://github.com/Peterande/D-FINE {dfine_root}\n"
            f"    pip install -r {dfine_root}/requirements.txt\n"
        )
    train_py = dfine_root / "train.py"
    if not train_py.exists():
        raise SystemExit(f"{train_py} not found; is {dfine_root} the D-FINE repo?")
    if not weights.exists():
        raise SystemExit(
            f"{weights} not found. Download the Objects365-pretrained D-FINE-L "
            f"checkpoint from the upstream release page and place it there. "
            f"The COCO-only checkpoint will also load, but carries markedly "
            f"less small-object supervision."
        )

    print("preflight")
    print(f"  train      {len(train['images']):>4} images, "
          f"{len(train['annotations']):>4} boxes ({negatives} negative)")
    print(f"  val        {len(val['images']):>4} images, "
          f"{len(val['annotations']):>4} boxes")
    print(f"  classes    {len(names)}  {names}")

    try:
        # numpy first, deliberately. In an Anaconda environment two copies of
        # libiomp5md.dll are reachable -- one from MKL, one shipped inside the
        # torch wheel -- and importing torch into a process that has not already
        # loaded the MKL copy aborts with OpenMP error #15 before a single line
        # of ours runs. Loading numpy first pins the MKL runtime, after which
        # torch attaches to it. Measured here: `import torch` alone aborts,
        # `import numpy, torch` succeeds.
        import numpy  # noqa: F401
        import torch
        if not torch.cuda.is_available():
            raise SystemExit(
                "no CUDA device is visible. This fine-tune is a GPU job; "
                "running it on CPU would take days and is not supported here."
            )
        name = torch.cuda.get_device_name(0)
        total = torch.cuda.get_device_properties(0).total_memory / 1e9
        print(f"  device     {name}, {total:.0f} GB")
    except ImportError:
        raise SystemExit("torch is not installed in this environment.")

    return train, val


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dataset", type=Path, default=Path("data/dataset"))
    ap.add_argument("--dfine-root", type=Path, default=Path("third_party/D-FINE"))
    ap.add_argument("--weights", type=Path,
                    default=Path("models/dfine/dfine_l_obj2coco.pth"))
    ap.add_argument("--output-dir", type=Path, default=Path("models/dfine/finetune"))
    ap.add_argument("--epochs", type=int, default=40)
    ap.add_argument("--batch-size", type=int, default=8)
    ap.add_argument("--lr", type=float, default=2.5e-4)
    ap.add_argument("--backbone-lr", type=float, default=2.5e-5)
    ap.add_argument("--config-out", type=Path,
                    default=Path("configs/dfine_classroom.yml"))
    ap.add_argument("--dry-run", action="store_true",
                    help="run the checks and write the config, then stop")
    args = ap.parse_args()

    dataset = args.dataset.resolve()
    dfine_root = args.dfine_root.resolve()
    preflight(dataset, dfine_root, args.weights.resolve())

    def posix(path: Path) -> str:
        return path.resolve().as_posix()

    config = CONFIG_TEMPLATE.format(
        dfine_root=posix(dfine_root),
        output_dir=posix(args.output_dir),
        weights=posix(args.weights),
        num_classes=len(BOX_CLASSES),
        # The exported file_name entries are absolute paths, so joining them
        # against any root leaves them unchanged. Set explicitly rather than
        # relied on silently.
        img_folder='""',
        train_ann=posix(dataset / "train.json"),
        val_ann=posix(dataset / "val.json"),
        batch_size=args.batch_size,
        epochs=args.epochs,
        lr=args.lr,
        backbone_lr=args.backbone_lr,
    )
    args.config_out.parent.mkdir(parents=True, exist_ok=True)
    args.config_out.write_text(config, encoding="utf-8")
    print(f"\nconfig written to {args.config_out}")

    command = [
        sys.executable, str(dfine_root / "train.py"),
        "-c", str(args.config_out.resolve()),
        "--use-amp", "--seed", "0",
    ]
    print("  " + " ".join(command))

    if args.dry_run:
        print("\n--dry-run: checks passed and the config is written; "
              "training not started.")
        return 0

    args.output_dir.mkdir(parents=True, exist_ok=True)
    return subprocess.call(command, cwd=str(dfine_root))


if __name__ == "__main__":
    raise SystemExit(main())
